name: Toosky-CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
      - run: python -c "print('Python is alive here in this machine!')"
      - name: Installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running test cases
        run: python -m unittest -v
