name: Toosky-CI

on: [push]

jobs:
  running_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: python -c "print('Python is alive here in this machine!')"
      - name: Installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up envs
        run: mv .env-example .env
      - name: Running test cases
        run: |
          ls -lh
          python scripts/create_tables.py
          ls -lh
          python -m unittest -v
